name: Docker

on:
  push:

jobs:
  push:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image for Windows
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PWD }}" 
          docker build --tag dev34253/yacoin-build:windows.latest .
          docker push dev34253/yacoin-build:windows.latest
