name: Docker

on:
  push:

jobs:
  push:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build image for Windows
        run: |
          docker build . --tag dev34253/yacoin-build:windows
